name: GLaDOS Sign-in Workflow

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜执行
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sign-in:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Successfully installed dependencies"

    - name: Set up environment variables
      run: |
        echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}" >> $GITHUB_ENV
        echo "TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}" >> $GITHUB_ENV
        echo "HTTP_PROXY=${{ secrets.HTTP_PROXY }}" >> $GITHUB_ENV
        echo "HTTPS_PROXY=${{ secrets.HTTPS_PROXY }}" >> $GITHUB_ENV
        echo "GLADOS_EMAIL_1=${{ secrets.GLADOS_EMAIL_1 }}" >> $GITHUB_ENV
        echo "GLADOS_COOKIE_1=${{ secrets.GLADOS_COOKIE_1 }}" >> $GITHUB_ENV

    - name: Run GLaDOS sign-in script
      run: |
        python glados_sign.py
      continue-on-error: true  # 即使有错误，也不会导致整个工作流失败

    - name: Check Python script logs
      run: |
        tail -n 10 glados_sign.py  # 打印最后 10 行日志，检查错误

    - name: Clean up
      run: rm -f glados_sign.py
